---
- name: Playbook hcloud_basic.yml
  hosts: label_ansible_student
  become: yes

  tasks:

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Installiere Basispakete
    apt: 
      name: "{{ item }}"
      state: latest
    loop: "{{ hosts_basic_packets }}"
